In [1]:
import numpy as np
import math
import sympy as sym
from IPython.display import Math


In [15]:
a1 = [1,2,3,4,5]

In [16]:
sum(a1)

15

In [17]:
np.sum(a1)

15

In [18]:
np.prod(a1)

120

In [19]:
np.cumsum(a1)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [7]:
a= np.array([[1,2,3],[4,5,6]])

In [8]:
display(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
from IPython.display import Math
import sympy as sym
display(Math(sym.latex(sym.simplify(a))))

<IPython.core.display.Math object>

In [12]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [21]:
a1

[1, 2, 3, 4, 5]

In [28]:
display(a1)

[1, 2, 3, 4, 5]

In [27]:
import matplotlib.pyplot as plt

In [26]:
import seaborn as sns

In [29]:
t=np.array([[1,2,3],[3,4,5],[6,7,8]])
y=np.array([[1,1,2],[1,2,1],[2,1,2]])

In [30]:
display(t)
display(y)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

array([[1, 1, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [36]:
display(Math(sym.latex(sym.simplify(t))))
display(Math(sym.latex(sym.simplify(y))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [39]:
display(Math(sym.latex(sym.simplify(t*y))))

<IPython.core.display.Math object>

In [40]:

display(Math(sym.latex(sym.simplify(t/y))))

<IPython.core.display.Math object>

In [42]:
#perkalian matriks
display(t.dot(t))


array([[ 25,  31,  37],
       [ 45,  57,  69],
       [ 75,  96, 117]])

In [43]:
np.sin(t)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [46]:
t==y

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [50]:
display(t.dot(t).transpose())

array([[ 25,  45,  75],
       [ 31,  57,  96],
       [ 37,  69, 117]])

In [51]:
display(t.ravel())

array([1, 2, 3, 3, 4, 5, 6, 7, 8])

In [53]:
display(t.reshape(9,1))

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [71]:
#penambahan array baris axis =0
n=np.append(t,[[2,2,8]], axis=0)

In [69]:
n

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [2, 2, 8]])

In [65]:
#penambahan array kolom axis=1
np.append(t,[[2,2,6]], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [81]:
np.delete(n,0,axis=0)

array([[3, 4, 5],
       [6, 7, 8],
       [2, 2, 8]])

In [88]:
g=np.array([2,6,9,6])
h=np.array([0,9,8,6])

In [89]:
np.concatenate([g,h])

array([2, 6, 9, 6, 0, 9, 8, 6])

In [91]:
l=np.array([[2,6],[9,6]])
m=np.array([[0,9],[8,6]])

In [92]:
np.concatenate([l,m],axis=0)

array([[2, 6],
       [9, 6],
       [0, 9],
       [8, 6]])

In [93]:
np.concatenate([l,m],axis=1)

array([[2, 6, 0, 9],
       [9, 6, 8, 6]])

In [94]:
np.vstack([l,m])

array([[2, 6],
       [9, 6],
       [0, 9],
       [8, 6]])

In [95]:
np.hstack([l,m])

array([[2, 6, 0, 9],
       [9, 6, 8, 6]])

In [97]:
display(Math(sym.latex(sym.simplify(l,m))))

<IPython.core.display.Math object>